services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./logs:/var/log/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 30s
      retries: 3
    networks:
      - db
    restart: unless-stopped

  backup:
    image: ubuntu
    volumes:
      - db:/var/lib/postgresql/data
      - ./myData:/backup
    command: sh -c "pg_dump -U postgres -F c stock > /backup/stock.dump"

  stock-api:
    container_name: stock-api
    image: ousmanevincent/gestion-stock
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/stock
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      LOG_PATH: /var/log/myapp/myapp.log
      JAVA_OPTS: "-Dlog4j.configuration=file:/app/log4j.properties"
    ports:
      - "8082:8082"
    volumes:
      - ./logs:/var/log/myapp
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
#  stock-client:
#    container_name: stock-client
#    image: ousmanevincent/gestion-stock-client
#    build:
#      context: client/angular
#      args:
#        api_base_url: http://localhost:8082
#    ports:
#      - "3000:5173"
#    depends_on:
#      - stock-api
#    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: