package com.ovd.gestionstock.exceptions;

public enum ErrorCodes {

    UTILISATEUR_NOT_FOUND(1000),
    UTILISATEUR_ALREADY_EXISTS(1010),
    UTILISATEUR_CHANGE_PASSWORD_OBJECT_NOT_VALID(1050),
    ROLE_NOT_FOUND(2000),
    ARTICLE_NOT_FOUND(3000),
    CATEGORY_NOT_FOUND(3000),
    CLIENT_NOT_FOUND(4000),
    ENTREPRISE_NOT_FOUND(5000),
    VENTE_NOT_FOUND(6000),
    COMMANDE_CLIENT_NOT_FOUND(7000),
    COMMANDE_FOURNISSEUR_NOT_VALID(7100),

    COMMANDE_FOURNISSEUR_NOT_FOUND(7700),
    COMMANDE_FOURNISSEUR_NON_MODIFIABLE(7101),
    COMMANDE_CLIENT_NON_MODIFIABLE(7001),
    COMMANDE_FOURNISSEUR_ALREADY_IN_USE(7500),
    FOURNISSEUR_NOT_FOUND(8000),
    ENTREPRISE_NOT_VALID(8500),
    VENTE_NOT_VALID(9000),

    VENTE_ALREADY_IN_USE(9100),
    MODE_PAYEMENT_NOT_FOUND(9300),
    UNITE_NOT_VALID(9500),
    MVT_STK_NOT_VALID(10000)
    ;

    private int code;

    ErrorCodes(int code) {
        this.code = code;
    }

    public int getCode() {
        return code;
    }

}
