#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: postgres
POSTGRES_SQL_HOST: postgres
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: stock

#Server
SERVER_PORT: 8082
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: dioneousmanevincent@gmail.com
EMAIL_PASSWORD: gcqauvtiwlnllbsn
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}