apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-deployment
  labels:
    app: postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: database
                  name: pg-config
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: pg-secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pg-secrets
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-pvc
      volumes:
        - name: pg-pvc
          persistentVolumeClaim:
            claimName: pg-pvc