apiVersion: v1
kind: Service
metadata:
  name: pg-service
  labels:
    app: pg-service
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: pg-service
  clusterIP: None