name: Build and deploy Gestion stock


on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy Spring boot gestion stock
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

#      - name: Unit Tests
#        run: mvn -B test --file pom.xml

      - name: Build the application ok
        run: |
          mvn clean 
          mvn package -DskipTests

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gestion-stock:$(date-'%Y%m%d%H%M%S')


      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gestion-stock:$(date-'%Y%m%d%H%M%S')
      
